### ISSUE TITLE
Incorrect timing with GD32F130C6T6

### ISSUE THREAD

**Issue by MrElectronicist** [CommunityGD32Cores/platform-gd32#29]
I am trying delay commands with my GD32F130C6T6 and the timing takes 10X longer than the delay. Not sure what needs changed to fix this issue

**Comment by maxgerhardt** [comment]
Well it's either an issue or in the discussions, but not both -- let's discuss this in https://github.com/CommunityGD32Cores/platform-gd32/discussions/28 further.
